name: "Validate Gradle Wrapper"

on:
    pull_request:
        branches: [ main, stable-* ]

jobs:
    validation:
        name: "Validation"
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v4.1.1
            -   uses: gradle/wrapper-validation-action@v1
